services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - '3000:3000'
    volumes:
      - 'C:\Users\ngobi\Desktop\Projects\work\side-hustle\portfolio:/app'
      - '/app/node_modules'
      - '/app/.next'
  